/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuildDto { 
    baseRole: BuildDto.BaseRoleEnum;
    subRoles?: Array<BuildDto.SubRolesEnum>;
}
export namespace BuildDto {
    export const BaseRoleEnum = {
        Dps: 'DPS',
        HealAlac: 'HEAL_ALAC',
        HealQuick: 'HEAL_QUICK',
        BoonAlac: 'BOON_ALAC',
        BoonQuick: 'BOON_QUICK',
        GenericHeal: 'GENERIC_HEAL',
        GenericBoonDps: 'GENERIC_BOON_DPS'
    } as const;
    export type BaseRoleEnum = typeof BaseRoleEnum[keyof typeof BaseRoleEnum];
    export const SubRolesEnum = {
        Portal: 'PORTAL',
        Kite: 'KITE',
        Lamp: 'LAMP',
        Pylon: 'PYLON',
        Handkite: 'HANDKITE'
    } as const;
    export type SubRolesEnum = typeof SubRolesEnum[keyof typeof SubRolesEnum];
}


