/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SlotRequest } from './slotRequest';


export interface CreateEventDto { 
    title?: string;
    description?: string;
    startTime?: string;
    endTime?: string;
    categoryId?: number;
    slots?: Array<SlotRequest>;
}

