/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEventDto } from './userEventDto';


export interface EventResponseShortDto { 
    id: number;
    title: string;
    startTime: string;
    endTime: string;
    category: string;
    organizer: UserEventDto;
    occupiedSlotsSize: number;
    slotsSize: number;
    neededRoles?: Array<string>;
}

