/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuildDto } from './buildDto';


export interface EventSignupDto { 
    targetSlotId: number;
    primaryBuild: BuildDto;
    flexBuilds?: Array<BuildDto>;
}

