/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryDto } from './categoryDto';
import { SlotDto } from './slotDto';
import { UserDto } from './userDto';


export interface EventResponseDto { 
    id?: number;
    title?: string;
    description?: string;
    startTime?: string;
    endTime?: string;
    category?: CategoryDto;
    organizer?: UserDto;
    slots?: Array<SlotDto>;
}

