/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuildDto } from './buildDto';
import { UserEventDto } from './userEventDto';


export interface SlotDto { 
    id: number;
    subgroup: number;
    requiredBuild: BuildDto;
    effectiveBuild: BuildDto;
    declaredPrimaryBuild?: BuildDto;
    actualBuild?: BuildDto;
    player?: UserEventDto;
    flexBuilds?: Array<BuildDto>;
    blocked?: boolean;
}

