/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SlotRequest { 
    subgroup: number;
    requiredBaseRole: SlotRequest.RequiredBaseRoleEnum;
    requiredSubRoles?: Array<SlotRequest.RequiredSubRolesEnum>;
}
export namespace SlotRequest {
    export const RequiredBaseRoleEnum = {
        Dps: 'DPS',
        HealAlac: 'HEAL_ALAC',
        HealQuick: 'HEAL_QUICK',
        BoonAlac: 'BOON_ALAC',
        BoonQuick: 'BOON_QUICK',
        GenericHeal: 'GENERIC_HEAL',
        GenericBoonDps: 'GENERIC_BOON_DPS'
    } as const;
    export type RequiredBaseRoleEnum = typeof RequiredBaseRoleEnum[keyof typeof RequiredBaseRoleEnum];
    export const RequiredSubRolesEnum = {
        Portal: 'PORTAL',
        Kite: 'KITE',
        Lamp: 'LAMP',
        Pylon: 'PYLON',
        Handkite: 'HANDKITE'
    } as const;
    export type RequiredSubRolesEnum = typeof RequiredSubRolesEnum[keyof typeof RequiredSubRolesEnum];
}


