/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';
import { UserEventDto } from './userEventDto';


export interface SlotDto { 
    id: number;
    role: RoleDto;
    player?: UserEventDto;
    flexRoles?: Array<RoleDto>;
    blocked?: boolean;
}

