/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: number;
    discordId?: string;
    username?: string;
    email?: string;
    avatarUrl?: string;
    gw2AccountName?: string;
    role?: string;
}

